Feat clippy
zkcrypto/bellman pull request #60
Opened 2021-01-25 05:56 UTC by zgfzgf

fix clippy warning

2021-01-25 08:45 UTC, zgfzgf commented
cargo 1.49.0 (d00d64df9 2020-12-05)
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.49.0 (e1884a8e3 2020-12-29)`

cargo build --verbose --release --tests    OK

2021-02-03 12:54 UTC, str4d requested changes
Most of the changes LGTM and address lints we are now seeing after #64.

2021-02-03 12:54 UTC, str4d commented on src/groth16/prover.rs
> +        AddAssign::<&E::G1>::add_assign(&mut g_c, &(vk.alpha_g1 * s));
These changes break compilation, so we can't address the clippy lint in this way.

2021-02-03 12:54 UTC, str4d commented on src/groth16/generator.rs
> +        delta_g2: (g2 * delta).to_affine(),
Ditto.

2021-02-03 12:54 UTC, str4d commented on src/lib.rs
> +#![deny(broken_intra_doc_links)]
We cannot make this change until MSRV is at least 1.48.0 (see https://github.com/zcash/librustzcash/issues/279).

2021-02-03 13:10 UTC, closed without merging